version: '3.7'

services:  

  nodered:
    image: kalemena/node-red:latest
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - ./data:/data
     # - /home/nodered/.node-red                  # Default User Directory
     # - /home/nodered/.node-red/settings.js      # Default Settings file
     # - /data/flows.json                         # Default Flows file
# Examples of mounting USB devices
#    devices:
#     - "/dev/ttyUSB0:/dev/ttyCurrenCost"
#     - "/dev/ttyUSB1:/dev/ttyJeeLink"
#     - "/dev/ttyUSB2:/dev/ttyRfxTrx"
#     - "/dev/ttyUSB3:/dev/ttyZigbee"
#     - "/dev/ttyUSB4:/dev/ttyZWave"
    environment:
     - NODERED_FLOWS=/data/flows.json
     - NODERED_USERDIR=/home/nodered/.node-red
     - NODERED_SETTINGS=/home/nodered/.node-red/settings.js
