version: '3.7'

services:  

  nodered:
    image: kalemena/node-red:latest
#    build: .
    restart: always
    ports:
     - "1880:1880"
    volumes:
     - ./data:/data
#     - ./etc/node-red/settings.js:/home/node-red/settings.js
     - ./etc/my-app:/etc/my-app
#    devices:
#     - "/dev/ttyUSB0:/dev/ttyCurrenCost"
#     - "/dev/ttyUSB1:/dev/ttyJeeLink"
#     - "/dev/ttyUSB2:/dev/ttyRfxTrx"
    environment:
     - FLOWS=/data/flows.json
