version: '3.7'

services:  

  nodered:
    image: kalemena/node-red:0.19.4
#    build: .
    restart: always
    ports:
     - "1880:1880"
    volumes:
     - ./data:/data
#    devices:
#     - "/dev/ttyUSB0:/dev/ttyCurrenCost"
#     - "/dev/ttyUSB1:/dev/ttyJeeLink"
#     - "/dev/ttyUSB2:/dev/ttyRfxTrx"
    environment:
     - FLOWS=/data/flows.json