:toc:

ifdef::env-github[]
image:https://img.shields.io/travis/kalemena/docker-node-red/master.svg[Travis build status, link=https://travis-ci.org/kalemena/docker-node-red]
image:https://images.microbadger.com/badges/version/kalemena/node-red.svg[Docker Version, link=https://microbadger.com/images/kalemena/node-red]
image:https://images.microbadger.com/badges/image/kalemena/node-red.svg[Docker Hub, link=https://hub.docker.com/r/kalemena/node-red/tags]
endif::[]

= docker-node-red

Packaged Node-Red for use in home automation.

== Build

[source,bash]
----
$ docker build -t kalemena/node-red .
----

== Run with compose

Run with opening 1880 port, and map your flows into /data directory.

Optionaly, map USB devices used in flows.

[source,bash]
.docker-compose.yml
====
include::docker-compose.yml[]
====

=== Start node-red

[source,bash]
----
$ docker-compose up -d
----

Now you can connect on *http://localhost:1880*

=== Stop node-red

[source,bash]
----
$ docker-compose stop
----

=== Remove container node-red

[source,bash]
----
$ docker-compose down
----

== Examples

Few samples are shared for faster rampup on Node-Red and usage of existing blocks

- link:examples/basics-csv-calendar-events[CSV Calendar reading & processing]
- link:examples/basics-websockets-chat-sentiment[Using WebSockets in Chat Room - example from FRED portal]
- link:examples/basics-mongodb-http-contacts-api[HTTP API & MongoDB storage for contact creation/identification]
- link:examples/basics-redis-http-scheduler-api[HTTP API & Redis storage for a scheduler API]

Other example based on my contribs:

- link:https://github.com/kalemena/node-red-contrib-libphonenumber[LibPhoneNumber example]