:toc:

ifdef::env-github[]
image:https://github.com/kalemena/docker-node-red/workflows/Pipeline/badge.svg[GitHub Build]
image:https://img.shields.io/docker/v/kalemena/node-red[Docker Hub, link=https://hub.docker.com/r/kalemena/connectiq/tags]
image:https://img.shields.io/docker/pulls/kalemena/node-red[Docker Hub, link=https://hub.docker.com/r/kalemena/connectiq/tags]
image:https://img.shields.io/docker/image-size/kalemena/node-red[Docker Hub, link=https://hub.docker.com/r/kalemena/connectiq/tags]
endif::[]

= docker-node-red

Packaged Node-Red for use in home automation.

== Build

[source,bash]
----
$ docker build -t kalemena/node-red .
----

== Run with compose

Run with opening 1880 port, and map your flows into /data directory.

Optionaly, map USB devices used in flows.

[source,bash]
.docker-compose.yml
====
include::docker-compose.yml[]
====

=== Start node-red

[source,bash]
----
$ docker-compose up -d
----

Now you can connect on *http://localhost:1880*

=== Stop node-red

[source,bash]
----
$ docker-compose stop
----

=== Remove container node-red

[source,bash]
----
$ docker-compose down
----

== Examples

Few samples are shared for faster rampup on Node-Red and usage of existing blocks

Simple flows:

- link:examples/basics-csv-calendar-events[CSV Calendar reading & processing]
- link:examples/basics-elasticsearch-http-contacts-api[HTTP API & ElasticSearch storage for contact creation/identification]
- link:examples/basics-mongodb-http-contacts-api[HTTP API & MongoDB storage for contact creation/identification]
- link:examples/basics-redis-http-scheduler-api[HTTP API & Redis storage for a scheduler API]
- link:examples/basics-telegram[Example Telegram usage]
- link:examples/basics-websockets-chat-sentiment[Using WebSockets in Chat Room - example from FRED portal]
- link:examples/zwave/flows-zwave-switch-onoff.json[ZWave sample]

Other example based on my contribs:

- link:https://github.com/kalemena/node-red-contrib-libphonenumber[LibPhoneNumber example]

Advanced flows:

- link:examples/chat-queue-telegram[Chat Websocket + REST API + Telegram]

== TODOs

link:todo.adoc[]