:toc:

ifdef::env-github[]
image:https://img.shields.io/travis/kalemena/docker-node-red/master.svg[Travis build status, link=https://travis-ci.org/kalemena/docker-node-red]
image:https://images.microbadger.com/badges/version/kalemena/node-red.svg[Docker Version, link=https://microbadger.com/images/kalemena/node-red]
image:https://images.microbadger.com/badges/image/kalemena/node-red.svg[Docker Hub, link=https://hub.docker.com/r/kalemena/node-red/tags]
endif::[]

= docker-node-red

Packaged Node-Red for use in home automation.

Runs node-red with few plugins like rfxtrx com.

== Build

[source,bash]
----
$ docker build -t kalemena/node-red .
----

== Run

Expose ports 1880 (node-red).

Mount volumes for your flows into /data using -v, and environment variable FLOWS pointing to the flows.json file. 

Attach your USB devices using --device.

[source,bash]
----
$ docker run --restart=always --name nodered --hostname nodered \
	-d -p 1880:1880 -p 1883:1883 \
	-v ./data:/data \
	--device=/dev/ttyUSB0:/dev/ttyRfxTrx \
	--device=/dev/ttyUSB1:/dev/ttyJeeLink \
	--device=/dev/ttyUSB2:/dev/ttyCurrenCost \
	-e FLOWS=/data/flows.json \
	kalemena/node-red
----

== Run with compose

Run with opening 1880 port, and map your flows into /data directory.

Optionaly, map USB devices used in flows.

[source,bash]
.docker-compose.yml
====
include::docker-compose.yml[]
====

=== Start node-red

[source,bash]
----
$ docker-compose up -d
----

Now you can connect on http://&lt;your host&gt;:1880

=== Stop node-red

[source,bash]
----
$ docker-compose stop
----

=== Remove container node-red

[source,bash]
----
$ docker-compose down
----

== Examples

- link:examples/contacts[Creating a simple API]
- link:examples/birthdayB[CSV reading]

== Interesting modules

To be checked:

* node-red-contrib-simple-weekly-scheduler
* node-red-contrib-rfxcom
* node-red-contrib-influxdb
* node-red-dashboard
* node-red-node-smooth 
* node-red-node-pidcontrol
* node-red-node-random
* node-red-node-mdns
* node-red-node-nma
* node-red-node-pushbullet
* node-red-node-daemon
* node-red-contrib-web-worldmap

```bash
# NODE RED Z-WAVE
# RUN \
#  yum install -y http://mirror.my-ho.st/Downloads/OpenZWave/CentOS_7/x86_64/libopenzwave-1.4.164-2.1.x86_64.rpm; \
#  yum install -y http://mirror.my-ho.st/Downloads/OpenZWave/CentOS_7/x86_64/openzwave-1.4.164-2.1.x86_64.rpm; \
#  cd /home; \
#  wget https://github.com/OpenZWave/open-zwave/archive/V1.5.zip; unzip V1.5.zip; rm V1.5.zip; \
#  cd open-zwave-1.5; \
#  yum install -y libudev-devel net-tools; \
#  make && make install; \
#  cd /home/node-red; \
#  npm install node-red-contrib-openzwave;
```