version: '3.7'

volumes:
  mongo-data:
  es-data:

services:  

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example

  nodered:
    build: .
    restart: always
    ports:
     - "1880:1880"
    volumes:
     - .:/data
    environment:
     - FLOWS=/data/flows.json