version: '3.7'

services:  

  nodered:
    build: .
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - .:/data
     - ./etc/node-red:/root/.node-red
     - ./var/log:/var/log
    environment:
     - FLOWS=/data/flows.json