version: '3.7'

volumes:
  redis-data:

services:  

  nodered:
    build: .
    restart: always
    ports:
     - "3880:1880"
    volumes:
     - .:/data
    environment:
     - FLOWS=/data/flows.json