version: '3.7'

volumes:
  redis-data:

services:  

  mqtt:
    image: eclipse-mosquitto:1.6
    restart: always

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM1:/dev/ttyACM1
    privileged: true
    environment:
      - TZ=Europe/Paris
    networks:
      default:
        aliases:
          - zigbee2mqtt.tidhome.local

  nodered:
    build: .
    restart: always
    ports:
     - "3880:1880"
    volumes:
     - .:/data
    environment:
     - FLOWS=/data/flows.json