version: '3.7'

# networks: 
#   default: 
#     external: 
#       name: external-ti-dhome 

volumes:
  influxdb-data:
  grafana-data:

services:  

  # mqtt:
  #   image: eclipse-mosquitto:1.6
  #   restart: always
  #   ports:
  #     - "1883:1883"

  influxdb2:
    image: influxdb:2.0.7
    # user: "${UID}:${GID}"
    restart: always
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes: 
      - influxdb2-data:/var/lib/influxdb2:rw
      - ./etc/influxdb2:/etc/influxdb2
      - ./etc/influxdb2/scripts:/docker-entrypoint-initdb.d
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      # Creds
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME:-default}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD:-password}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG:-tidhome-org}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET:-tidhome-bucket}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-secret-auth-token}
      # Retention
      DOCKER_INFLUXDB_INIT_RETENTION: ${DOCKER_INFLUXDB_INIT_RETENTION:-4w}

  # grafana:
  #   image: grafana/grafana
  #   # user: "${UID}:${GID}"
  #   restart: always
  #   ports:
  #     - "${GRAFANA_PORT:-3000}:3000"
  #   volumes:
  #     # - ./etc/grafana:/etc/grafana
  #     # - ./var/lib/grafana:/var/lib/grafana
  #     # - ./var/log/grafana:/var/log/grafana
  #     - grafana-data:/var/lib/grafana
  #     - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
  #   environment:
  #     GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-default}
  #     GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-password}
  #   env_file:
  #     - .env

  nodered:
    #image: kalemena/node-red:latest
    build: .
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - .:/data
     # - ./workspace/nodered:/home/nodered/.node-red
     # - ./workspace/log:/var/log
    environment:
     FLOWS: /data/flows.json
     NODERED_CREDENTIAL_SECRETS: ${NODERED_CREDENTIAL_SECRETS:-xoxoxoxo}
     