
############################
# Manages life cycle
############################
start: 
	docker-compose up -d

stop:
	docker-compose stop

down:
	docker-compose down

clean:
	docker-compose down --volumes

############################
# Troubleshoot
############################

logs:
	docker logs -f integration-node-red-contrib-influxdb2_influxdb2_1

