FROM kalemena/node-red:2.1.6

RUN npm i   node-red-contrib-redis \
            node-red-contrib-uuid \
            node-red-contrib-moment \
            node-red-contrib-telegrambot \
            node-red-node-sentiment \
            node-red-contrib-google-translate-fixed