
volumes:
  nodered:
  matterbridge:

services:  

  # browse : http://localhost:8283
  matterbridge:
    image: luligu/matterbridge:latest
    restart: always
    network_mode: host
    volumes:
      - matterbridge:/root
      - ./matterbridge-zigbee2mqtt.config.json:/root/.matterbridge/matterbridge-zigbee2mqtt.config.json
    # ports:
    #   - 8283:8283

  # browse : http://localhost:3880
  nodered:
    build: .
    restart: always
    ports:
     - "3880:1880"
    volumes:
     - nodered:/data
     - ./flows.json:/data/flows.json:rw
    environment:
     - FLOWS=/data/flows.json