
volumes:
  nodered:

services:  

  nodered:
    build: .
    restart: always
    ports:
     - "3880:1880"
    volumes:
     - nodered:/data
     - ./flows.json:/data/flows.json
    environment:
     - FLOWS=/data/flows.json