version: '3.7'

volumes:
  influxdb-data:
  grafana-data:

services:  

  influxdb:
    image: influxdb
    # user: "${UID}:${GID}"
    restart: always
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes: 
      - influxdb-data:/var/lib/influxdb:rw
      - ./etc/influxdb/scripts:/docker-entrypoint-initdb.d
    environment:
      # Memory usage reduction (bugs after sometimes)
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_MONITOR_STORE_ENABLED: "false"
      INFLUXDB_META_LOGGING_ENABLED: "true"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
      # Creds
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-default}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-password}
      INFLUXDB_USER: ${INFLUXDB_USER:-default}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-password}
      # Default DB    
      # INFLUXDB_DB: "telegraf"

  grafana:
    image: grafana/grafana
    # user: "${UID}:${GID}"
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-default}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-password}

  nodered:
    #image: kalemena/node-red:latest
    build: .
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - .:/data
     # - ./workspace/nodered:/home/nodered/.node-red
     # - ./workspace/log:/var/log
    environment:
     FLOWS: /data/flows.json
     NODERED_CREDENTIAL_SECRETS: ${NODERED_CREDENTIAL_SECRETS:-xoxoxoxo}
     