version: '3.7'

volumes:
  mongo-data:
  es-data:

services:  

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example

  elasticsearch:
    image: elasticsearch:7.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  nodered:
    build: .
    restart: always
    ports:
     - "2880:1880"
    volumes:
     - .:/data
    environment:
     - FLOWS=/data/flows.json