version: '3.7'

services:  

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  nodered:
    image: kalemena/node-red:0.20.3
    restart: always
    ports:
     - "2880:1880"
    volumes:
     - .:/data
     - ../../etc/node-red/settings.js:/home/node-red/settings.js
    environment:
     - FLOWS=/data/flows.json