version: '3.7'

volumes:
  webdav-data:

services:  

  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Basic
      USERNAME: test
      PASSWORD: test1234
    volumes:
      - webdav-data:/var/lib/dav

  nodered:
    #image: kalemena/node-red:latest
    build: .
    restart: always
    ports:
     - "${NODERED_PORT:-1880}:1880"
    volumes:
     - .:/data
     # - ./workspace/nodered:/home/nodered/.node-red
     # - ./workspace/log:/var/log
    environment:
     - FLOWS=/data/flows-webdav.json
     