version: '3.7'

services:  

  nodered:
    #image: kalemena/node-red:latest
    build: .
    restart: always
    ports:
     - "${NODERED_PORT:-3880}:1880"
    volumes:
     - ./etc/node-red:/home/nodered/.node-red
    #  - ./etc/node-red/flows:/home/nodered/.node-red/flows
    #  - ./etc/node-red/config-nodes.yaml:/home/nodered/.node-red/config-nodes.yaml
    #  - ./etc/node-red/flow-manager-cfg.json:/home/nodered/.node-red/flow-manager-cfg.json
    #  - ./etc/node-red/settings.js:/home/nodered/.node-red/settings.js
     # - ./workspace/nodered:/home/nodered/.node-red
     # - ./workspace/log:/var/log
    environment:
     - FLOWS=/data/flows-node-red-contrib-flow-manager.json
     