version: '3.7'

volumes:
  redis-data:

services:  

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  nodered:
    build: .
    restart: always
    ports:
     - "3880:1880"
    volumes:
     - .:/data
    environment:
     - FLOWS=/data/flows.json