name: Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      env:
        IMAGE: "kalemena/node-red"
        VERSION: "1.0.3"
      run: |
        docker -v
        docker pull centos:7
        docker pull ${IMAGE}:${VERSION} || true
        docker build --pull --cache-from ${IMAGE}:${VERSION} \
          -t ${IMAGE}:${VERSION} \
          -f Dockerfile \
          --build-arg NODERED_VERSION=${VERSION} \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=`git rev-parse --short HEAD` \
          --build-arg VERSION=${VERSION} .
        docker ps -a
        docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
        docker images
    # - name: Build & Publish Docker Image
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: kalemena/node-red:1.0.3
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}