name: Build & Publish Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        NODERED_VERSION: 1.0.3
      with:
        name: kalemena/node-red:${NODERED_VERSION}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: NODERED_VERSION
