name: Build & Publish Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        IMAGE: kalemena/node-red
        VERSION: 1.0.3
        NODERED_VERSION: 1.0.3
      with:
        name: ${IMAGE}:${VERSION}
        snapshot: ${IMAGE}:latest
        buildargs: IMAGE,VERSION,NODERED_VERSION
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
