name: Build & Publish Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t ${IMAGE}:${VERSION} -f Dockerfile --build-arg NODERED_VERSION=${VERSION} --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg VERSION=${VERSION} .
      env:
        IMAGE: kalemena/node-red
        VERSION: 1.0.3
    # - name: Retag as latest
    #   run: docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
    #   env: 
    #     IMAGE: kalemena/node-red
    #     VERSION: 1.0.3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kalemena/node-red:1.0.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
